name       : qtstyleplugins
version    : 5.0.0
release    : 7
source     :
    - git|https://code.qt.io/qt/qtstyleplugins.git : 335dbece103e2cbf6c7cf819ab6672c2956b17b3
license    :
    - LGPL-2.1
summary    : Provides GTK2 style integration for Qt applications
component  : desktop.qt
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(Qt5Widgets)
description: |
    Provides GTK2 style integration for Qt applications
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
    install -D -m 00644 $pkgfiles/50-qt-theming.sh $installdir/usr/share/defaults/etc/profile.d/50-qt-theming.sh
